go.mod, go.sum, gochain.go, main.go
```
$ web3-cli snapshot
11:07PM INF Snapshot details Snapshot={"hash":"0x0823315e6edb554ff267141c56508dde55d083ee6ac5519187ba17f3cd1ad327","number":4149859,"signers":{"0x03771ec9c739c2767be58256def7564678985c78":4149854,"0x1324567409b771d09a6abdb4af249b7fe2de45fc":4149853,"0x1ee4baf2cccc633b8e2c06a3ac20319610cf3cd5":4149856,"0x22d68b3bf15b37605c29e2477ef55729593cf40a":4149847,"0x3729d2e93e8037f87a2c9afe34cb84b7069e4dea":4149852,"0x3ad14430951aba12068a8167cebe3ddd57614432":4149850,"0x4707bae73acb61452afd3827263d8fce236dc0ee":4149846,"0x48c67d87cd7d716ec044dbe33a0152557bf86062":4149857,"0x4ed78f888e3d8f9f50e3f23e0ff2cf55550015bd":4149844,"0x76c8b15940c5b0775389d4e6adb854182930a0ee":4149859,"0x95dddf0006c6a2cae3d719efda527ce7ff8bef9c":4149843,"0xd707552e5cc8e894d76fd0c82eb368c2f3a4af1a":41498 …
```
=> add snapshot

main.go
This PR proposes adding a `-testnet` flag as a shortcut for `-network testnet`, sets the default network to `mainnet`, and simplifies some code.
```
web3-cli -testnet sn
{
"number": 3454853,
"hash": "0x9302f5daaa830a355912bf438f2c9e5669586de5c7c7bddeef1c5aba3705e3aa",
"signers": {
"0x10a8a552c8a8945f32f6fded5e44d9101b3491d8": 3454853,
"0x5ece2ae4109836b90af4a3dee896e40d6a227e61": 3454849,
"0x6e2cad5118b75420f7d73cfbd6db072523de8366": 3454850,
"0x7aeceb5d345a01f8014a4320ab1f3d467c0c086a": 3454852,
"0xdd7e460302a911f9162a208370cdcdc37b892453": 3454851
},
"voters": {
"0x7aeceb5d345a01f8014a4320ab1f3d467c0c086a": {}
},
"votes": [],
"tally": {}
}
```
```
web3-cli sn
{
"number": 4226459,
"hash": "0x1c9a4fa6e308488a16c61144e5104f765a8b4784261897d658a9b9619fe9706d",
"signers": { …
```
=> add testnet flag; simplify code

gochain.go
Additional check for a key length before removing bytes
=> Error on deploy #10

gochain_test.go, main.go
This PR adds some testable examples which call a few main and test methods. Fixes #12
=> add some testable examples

go.mod, go.sum, main.go
This PR adds human readable output. Fixes #18.
It is currently behind the `-human` flag, but perhaps should become the default, with the raw JSON fields behind some other flag.
=> WIP: add human readable output flag

client.go, cmd/web3/main.go, types.go, web3.go
added the feature that allows to make function calls
=> Function calls

README.md, contracts/README.md, contracts/hello.sol
=> Creating a quickstart tutorial

cmd/web3/main.go
This PR tweaks some command usage descriptions and other log output.
=> polish command usages

client.go, cmd/web3/main.go
```sh
> web3 bl 0x89230da077cc2389b4cc95394a01317fedfbb06163c88dcd6fa09294e690276f
Number: 4000000
Time: 2019-01-02T12:59:25Z
Transactions: 15
Gas Used: 315000/136500000 (0.23%)
...
```
=> get block by hash

cmd/web3/main.go, cmd/web3/start.go
Before:
```sh
___  _____  ___  _   _    __    ____  _  _ 
/ __)(  _  )/ __)( )_( )  /__\  (_  _)( \( )
( (_-. )(_)(( (__  ) _ (  /(__)\  _)(_  )  ( 
\___/(_____)\___)(_) (_)(__)(__)(____)(_)\_)
```
After:
```sh
___  _____  ___  _   _    __    ____  _  _ 
/ __)(  _  )/ __)( )_( )  /__\  (_  _)( \( )
( (_-. )(_)(( (__  ) _ (  /(__)\  _)(_  )  ( 
\___/(_____)\___)(_) (_)(__)(__)(____)(_)\_)
```
=> cmd/web3: wire in existing interrupt cancellation; fix ASCII art alignment

cmd/web3/main.go
This PR changes receipt details to print a human readable status instead of an integer.
=> cmd/web3: human readable receipt statuses

cmd/web3/main.go
This PR adds support for recognizing a private key from the `address` command (flag or env, only used when no address param is provided), and errors when neither address or private key is provided. Previously omitting an address would appear to be successful, but always return a 0 balance.
=> cmd/web3: address - error when missing; recognize private key

Makefile, assets/erc20.go, cmd/web3/main.go, cmd/web3/version.go
Cleans up the generated code.
Closes #81
=> Gen cleanup

.gitignore, README.md, assets/OwnerUpgradeableProxy.sol, assets/UpgradeableProxy.sol, assets/owner_upgradeable_proxy.go, cmd/web3/main.go, contracts/goodbye.sol
I'm still debugging an issue where the storage is not persisting across contract changes. The `README` has been updated to include an "upgrade" section and that works against `master`.
=> Upgradeable contracts

cmd/web3/main.go, rpc.go, types.go
This PR completes the set of receipt fields.
=> more receipt fields

assets/erc721.go, cmd/web3/generate.go, cmd/web3/main.go
Makes mintable and burnable true by default. Can use `--unmintable` and `--unburnable` to reverse that. 
Also adds `setTokenURI`method to erc721's by default. 
Closes #106
=> Gen new defaults

abi_wrapper.go, cmd/web3/contracts.go, cmd/web3/main.go, web3.go
Adds a get ABI by URL method and an overarching GetABI method that will get built ins, from a file or from a URL.
=> Adds exported GetABI method

web3.go
Follow up from #132 to restore `float64` handling and integer conversion, expand to some more integer cases, and add tests.
=> restore and expand ConvertArguments cases; add tests

.gitignore, web3.go, web3_test.go
This PR fixes a conversion bug blocking a 0 value for an unsigned field, and adds a previously .gitignored test file.
=> fix negative unsigned convert; add tests

cmd/web3/main.go
=> improve parameter validation #118

README.md, cmd/web3/main.go, web3.go
```
./web3 -testnet contract deploy ERC20.bin
Contract has been successfully deployed with transaction: 0x0c308984154a8029d7fad8d53057719e44a2a79d8d8bd62ddc950f4a9502ce20
Contract address is: 0x6F8c9989250F81ac93e3f38e57701D261fD594DD
./web3 contract verify --explorer-api https://testnet-explorer.gochain.io/api --address 0x6F8c9989250F81ac93e3f38e57701D261fD594DD  --contract-name ERC20 ERC20Burnable_flatten.sol
Your contract is successfully verified
```
=> verify a contract

cmd/web3/flatten.go, cmd/web3/main.go
This PR adds `-output` support to the `build` command.
=> expand output support

cmd/web3/main.go, solc.go
This change exposes some existing internal options as command line flags for more flexibility.
Fixes #171
=> add evm-version option to deploy and verify; add optimize option to verify

.github/workflows/main.yml
Pass `VERSION` env var through to mac step.
=> ci: pass VERSION to mac build

web3.go
Allow to deploy a contract from HTTP URL
=> DeployBin from http

assets/erc20.go, assets/erc721.go, cmd/web3/generate.go, solc.go
=> Fixes solidity 0.8.X breaking changes

cmd/web3/main.go, web3.go
=> removes currency name from balance

web3.go, web3_test.go
=> support FixedBytesTy params other than 32

web3.go, web3_test.go
=> convert to byte array for FixedBytesTy

cmd/web3/contracts.go
=> Regression bug fix

cmd/web3/contracts.go, cmd/web3/main.go, cmd/web3/transactions.go
=> Don't require abi if data passed in

cmd/web3/main.go
=> Added --gas-price and --gas-price-gwei as options to contract deploy

cmd/web3/contracts.go, cmd/web3/did.go, cmd/web3/main.go
This PR adds:
* Logging the transactionHash when a transaction fails
* --timeout flag to provide a timeout when waiting for transactions
=> Added logging transactionHash if a transaction failed + timeout in seconds

cmd/web3/contracts.go, cmd/web3/did.go, cmd/web3/main.go, cmd/web3/transactions.go
@treeder PTAL
(fix for https://github.com/gochain/web3/pull/261)
=> adding timeout for contracts depoy and function calls (receipts)

networks.go
I'm adding sepolia test net
@treeder
=> Sepolia test-net

cmd/web3/main.go, cmd/web3/transactions.go, vyper/compiler.go
=> chore: fix some comments
