gochain/web3

gochain.go, main.go, solc.go
This PR adds interrupt cancellation by wiring around a `context.Context`, allowing users to kill hung commands.
```
web3-cli -network testnet sn
^C2019/01/15 09:50:15 Cannot get snapshot from the network: Post https://testnet-rpc.gochain.io: context canceled
```
=> wire up ctx with signal interrupt cancellation

gochain.go, main.go
This PR adds an `id` command to show network id, chain id, and genesis hash.
```sh
web3-cli id
Network ID: 60
Chain ID: 60
Genesis Hash: 0x5b44a92a842a888b8b7cc1ff7eaac9800edf88a6a5f3d38850deb63d46acd880
web3-cli -testnet id
Network ID: 31337
Chain ID: 31337
Genesis Hash: 0x84337e882fad5883e2ed6e587ab5bdf711b7107a39abe8e080784bb30c8f047e
web3-cli -network ethereum id
Network ID: 1
Chain ID: 1
Genesis Hash: 0x03e43b36e734240240ab517dad42cc964a79122a487b9744fc4c7ff61a4c5c28
web3-cli -network ropsten id
2019/01/18 10:45:45 Failed to get chain ID: Method not found
Network ID: 3
Chain ID: <nil>
Genesis Hash: 0xa8a134fa3b1e1028a7811807fdd689c1cc0886e85012b2833cad4f72f532e2c6
```
=> add id command

client.go, cmd/web3/main.go
This PR adds a `receipt` command.
```sh
> web3 -testnet rc 0x3624d7a760d414e593cfe8b0349871a26414daa8ea9a707f56f6927852ff4de3
TxHash: 0x3624d7a760d414e593cfe8b0349871a26414daa8ea9a707f56f6927852ff4de3
GasUsed: 22192
Cumulative Gas Used: 22192
Status: 0
Post State: 0x
Bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Logs: [] …
```
=> add receipt command

client_test.go, cmd/web3/main.go, web3.go
This PR changes the output of the address command to use base units instead of wei, and changes the units based on the network (`GO`/`ETH`).
Old:
```sh
> web3 -n localhost addr 0x634639241b1a25F2c7eEe5222D8eB929d6D14f42
Balance: 1000000000000000000000
Code: 
```
New:
```sh
> web3 addr 0x76C8B15940C5b0775389d4e6aDB854182930A0ee
Balance: 93329.275369019905580000 GO
> web3 -n ethereum addr 0x76C8B15940C5b0775389d4e6aDB854182930A0ee
Balance: 0.000000000000000000 ETH
```
=> print balance in base units instead of wei; change base units with network

cmd/web3/main.go
This PR fixes the following error when trying to use the `-testnet` flag:
`Cannot set both network "gochain" and testnet`
=> cmd/web3: fix testnet flag

client.go, cmd/web3/main.go, rpc.go, types.go
This PR adds a `-tx` flag to the `block` command, and an `-input` flag to the `block` and `tx` commands. 
```sh
OPTIONS:
--tx value     Transaction format: count/hash/detail (default: "count")
--input value  Transaction input data format: len/hex/utf8 (default: "len")
```
Before this change, only transaction hashes were fetched with blocks, only the count was displayed in the human readable output, and input data was always left out. Now the user may choose whether to display block transactions as `count`, `hash`, or `detail` - the default is `count` (the pre-existing behavior). For `hash` and `detail`, each tx is printed on a line following its index in the block (`detail` works with `-format json` as well). Users may also choose whether to display tx input data as `len`, `hex`, or …
=> support either tx hashes or full details; output tx input data in various formats

web3.go
This PR adds checks to make sure the contract address is not blank, otherwise an attempted contract call can become an unintentional deploy, because the `to` field ends up blank.
=> check for missing address

cmd/web3/main.go
This PR proposes adding an `env` command to list out relevant environment variables and their values:
```sh
> web3 env
WEB3_ADDRESS=0x1
WEB3_NETWORK=testnet
WEB3_PRIVATE_KEY=0x1234
WEB3_RPC_URL=
```
=> cmd/web3: add 'env' command for inspecting env vars

cmd/web3/main.go, web3.go
This PR modifies WaitForReceipt by removing the fixed timeout (leaving it up to the caller instead), and only retrying `NotFoundErr` while returning other real errors.
=> remove fixed timeout from WaitForReceipt

cmd/web3/main.go, web3.go
This PR restores the ability to call the block subcommand without an argument to get the latest block.
=> fix latest block

README.md, cmd/web3/main.go, web3.go
This PR adds support for constructor params when deploying a contract. This requires the `.abi` in addition to the `.bin` (assumes they are collocated and only differ in extension). Any additional arguments are interpreted as parameters.
@benbjohnson Can we use this in place of the string find/replace used in upgradeable constructors?
=> allow constructor params

cmd/web3/main.go
We lost some default `WaitForReceipt` timeouts from simultaneous PRs. This restores the 10s wait to all calls. We may want to revisit and make some of these unlimited, so the user can wait as long as they want and control when to cancel.
=> fix receipt wait timeouts

client.go, client_test.go, cmd/web3/main.go, cmd/web3/version.go
This PR adds support for creating a `web3.Client` from an `rpc.Client` instead of dialing a new one.
=> support creating a client from rpc.Client

solc.go
I noticed that web3 was leaking old dead docker containers on my system, and this did the trick cleaning up nicely.
=> stop "web3 build" from leaking docker containers

README.md, cmd/web3/contracts.go, cmd/web3/main.go, web3.go
Uses floats to interact instead of huge ints. Supports erc20 balances and transfers too. 
examples:
``` sh
web3 balance
web3 transfer 0.1 to 0xAAAA
web3 balance --erc20
web3 transfer --erc20 0.1 to 0xAAAA
```
=> Some UX cleanup

assets/erc20.go, assets/erc721.go, cmd/web3/main.go, contracts/goodbye.sol, contracts/hello.sol, contracts/types.sol
Changed the pausable option to true by default because it's best practice for most tokens. And it's a lot better to have this and not want it than to not want it and have it since there is no going back.
=> Upgrade solidity and make pausable the default

web3.go, web3_test.go
This PR proposes adding `ConvertArguments()` support for `json.Number` and possibly removing support for `float64`, for the follow reasons:
`ExampleConvertArgumentsFromJSONLossy` demonstrates two cases where using the `encoding/json` default of `float64` for numbers is not accurate. Rounding can occur during JSON deserialization which is not caught by the exactness check in `ConvertArguments()` (and in fact, it _cannot be detected_ - the information is lost beforehand).
```go
func ExampleConvertArgumentsFromJSONLossy() {
args := abi.Arguments{abiUint(64), abiUint(64)}
jsonStr := `[10000000000000000.1, 10000000000000001]`
// Expectation: The first parameter should be rejected as 'not exact',
// and the second should pass through with full precision.
fmt.Println("JSON:", jsonStr)
var params …
```
=> ConvertArguments: support json.Number and reject float64

.github/workflows/main.yml
Github Actions will mark a check as "neutral" (neither failed/succeeded) when you exit with code 78. This will however cancel any other actions running in parallel in this workflow.
=> GitHub Actions CI issues #130

.github/workflows/main.yml
attempt to fix mac build versioning (it won't get the same version as linux because it don't checkout the latest code and shouldn't). So just bumping the version in the same way as linux.
=> updating github actions script ( #130)

assets/erc20.go, cmd/web3/flatten.go, cmd/web3/generate.go, cmd/web3/main.go
It adds a line at the top like:
```
// @openzeppelin v2.5.0
```
Then when it's being built and the openzeppelin libs aren't there, it will pull the right version. 
We were pulling master which is already working towards next version of solidity, 0.6.X, and it doesn't have ERC20Mintable anymore so it was breaking. This should fix issues like that.
=> Lock in openzeppelin version on generated files (and a bit of clean up)

cmd/web3/generate.go, go.mod, go.sum, web3.go, web3_test.go
This PR upgrades `gochain` to `v3.3.3` and reacts to API changes.
Fixes #147
=> upgrade to gochain v3.3.3

cmd/web3/main.go
This allows us to skip contract verification after deploy if we didn't supply contract source code.
=> Skip verify after deploy if no contract source

cmd/web3/did.go, cmd/web3/main.go, web3.go
This PR enables setting a `-gas-limit` to override the default of 2,000,000, which was causing https://github.com/gochain/gochain/issues/413
It also adds some tx receipt status checks.
=> add gas-limit flag to deploy

client.go, types.go
web3 contract call has no option to set the from address. The rpc call was using a from of `0x0000000000000000000000000000000000000000`. The spec shows the From field is optional, so this patch leaves the from field out of the call when the value is nil. 
This is more of a compliance feature than a fix. I ran info this problem by using msg.sender in a view function, but fixed that by passing the address explicitly as a parameter.
=> leave out an empty From address on eth_call

client.go, cmd/web3/contracts.go, cmd/web3/did.go, cmd/web3/main.go, cmd/web3/transactions.go, networks.go, types.go, web3.go
This change adds `Network.ChainID` for known networks and logic for fetching it for unknown RPC URLs, in order to use with signing transactions more securely with EIP155.
Fixes #201
=> EIP155: sign with chainID

install.sh
`uname -i` was return "unknown". This explains why: https://bugzilla.redhat.com/show_bug.cgi?id=548834#c5
=> Change from `uname-i` to `uname -m`

install.sh
Fixes the `install.sh` script for Mac Arm64 machines
=> fix installer for mac arm64

contracts/voting.sol
Added voting.sol to the `contracts` directory, this is a sample contract for voting (super common use of smart contracts) and I might add something in contracts.go in the future to support making voting SCs.
=> Added voting.sol to contracts

Dockerfile
This is a fix for #291 and it installs git binary to the Docker image in order to be able to use web3 image for [Generating Common Contracts](https://github.com/gochain/web3#generating-common-contracts).
A single drawback is that size will slightly increase
```shell
docker images -a | grep web3
web3-git       latest   0a9e9c666a5f   44 seconds ago   58MB
gochain/web3   latest   88dded04d5cb   5 months ago     42MB
```
=> Add git to the Docker image

web3.go
strings.Split on empty string results in a slice with one empty string ([""]) instead of 0-length ([]).
=> Fix cli error on empty input array #294
